name: 🚀 Build y Despliegue a Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Obtener código
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # La versión recomendada para Vite

      - name: 🛠️ Instalar y Compilar (Build)
        run: |
          npm install
          npm run build

      - name: 🔄 Subir carpeta DIST a Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Probamos sin public_html/ por si el FTP ya apunta allí
          local-dir: ./dist/ 
          server-dir: orlaspujaltefotografia/
          protocol: ftp
          port: 21
          dangerous-clean-slate: true
